// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC41HxmKLFtNxzqV7AAH46oEE2g2X2ajNk',
    appId: '1:672504296698:web:a088c8204b80c88b4b0543',
    messagingSenderId: '672504296698',
    projectId: 'fitplan-pro-677a0',
    authDomain: 'fitplan-pro-677a0.firebaseapp.com',
    storageBucket: 'fitplan-pro-677a0.firebasestorage.app',
    measurementId: 'G-2NRQPKGXE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0QKE32PXkNLTcXX13hWp5o29Cnqx_dXI',
    appId: '1:672504296698:android:d5d947d97ebd69ab4b0543',
    messagingSenderId: '672504296698',
    projectId: 'fitplan-pro-677a0',
    storageBucket: 'fitplan-pro-677a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSDJbXQ8ZDDoDWuJGP-hftVk4qx3EKg_0',
    appId: '1:672504296698:ios:14d19db3d5e436ed4b0543',
    messagingSenderId: '672504296698',
    projectId: 'fitplan-pro-677a0',
    storageBucket: 'fitplan-pro-677a0.firebasestorage.app',
    iosBundleId: 'com.example.bitirmeProjesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSDJbXQ8ZDDoDWuJGP-hftVk4qx3EKg_0',
    appId: '1:672504296698:ios:14d19db3d5e436ed4b0543',
    messagingSenderId: '672504296698',
    projectId: 'fitplan-pro-677a0',
    storageBucket: 'fitplan-pro-677a0.firebasestorage.app',
    iosBundleId: 'com.example.bitirmeProjesi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC41HxmKLFtNxzqV7AAH46oEE2g2X2ajNk',
    appId: '1:672504296698:web:de9c5deb2e117c044b0543',
    messagingSenderId: '672504296698',
    projectId: 'fitplan-pro-677a0',
    authDomain: 'fitplan-pro-677a0.firebaseapp.com',
    storageBucket: 'fitplan-pro-677a0.firebasestorage.app',
    measurementId: 'G-LVCN5BRZ29',
  );
}
